name: 'flutter build android'
  on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
  permissions:
    contents: read
    # Needed for the 'trilom/file-changes-action' action
    pull-requests: read
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.9'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
